// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyHub.Payment.Db;

namespace StudyHub.Payment.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211111060948_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudyHub.Payment.DomainServices.Merchant", b =>
                {
                    b.Property<Guid>("MerchantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("MerchantId");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("StudyHub.Payment.DomainServices.PaymentModel", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalShopperIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentOrderUniqueIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("StudyHub.Payment.DomainServices.Merchant", b =>
                {
                    b.OwnsOne("StudyHub.Payment.DomainServices.CardInformation", "CreditCardInformation", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CardNumber")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("Ccv")
                                .HasMaxLength(5)
                                .HasColumnType("int");

                            b1.HasKey("MerchantId");

                            b1.ToTable("Merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId");

                            b1.OwnsOne("StudyHub.Payment.DomainServices.ExpiryDate", "ExpiryDate", b2 =>
                                {
                                    b2.Property<Guid>("CardInformationMerchantId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Month")
                                        .HasColumnType("int");

                                    b2.Property<int>("Year")
                                        .HasColumnType("int");

                                    b2.HasKey("CardInformationMerchantId");

                                    b2.ToTable("Merchants");

                                    b2.WithOwner()
                                        .HasForeignKey("CardInformationMerchantId");
                                });

                            b1.Navigation("ExpiryDate");
                        });

                    b.Navigation("CreditCardInformation");
                });

            modelBuilder.Entity("StudyHub.Payment.DomainServices.PaymentModel", b =>
                {
                    b.OwnsOne("StudyHub.Payment.DomainServices.CardInformation", "CreditCardInformation", b1 =>
                        {
                            b1.Property<Guid>("PaymentModelPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CardNumber")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("Ccv")
                                .HasMaxLength(5)
                                .HasColumnType("int");

                            b1.HasKey("PaymentModelPaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentModelPaymentId");

                            b1.OwnsOne("StudyHub.Payment.DomainServices.ExpiryDate", "ExpiryDate", b2 =>
                                {
                                    b2.Property<Guid>("CardInformationPaymentModelPaymentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Month")
                                        .HasColumnType("int");

                                    b2.Property<int>("Year")
                                        .HasColumnType("int");

                                    b2.HasKey("CardInformationPaymentModelPaymentId");

                                    b2.ToTable("Payments");

                                    b2.WithOwner()
                                        .HasForeignKey("CardInformationPaymentModelPaymentId");
                                });

                            b1.Navigation("ExpiryDate");
                        });

                    b.OwnsOne("StudyHub.Payment.DomainServices.PaymentAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentModelPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("CurrencyCode")
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)");

                            b1.HasKey("PaymentModelPaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentModelPaymentId");
                        });

                    b.Navigation("Amount");

                    b.Navigation("CreditCardInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
